---
initial_entries: 10
randomize: true
search_index: id
username: {{.firstname}}{{.lastname}}
id: {{.firstname}}.{{.lastname}}
email: {{.firstname}}.{{.lastname}}@{{.company}}.com
created: {{.createdtimestamp}}
lastAccess: {{.itemtimestamp}}
token: {{.token}}
password: tempPASS
...
